x=[0 1 2 3 2 1];
h=[1 1 1 1 1 1];
nx=(0:1:5);
nh=(0:1:5);
subplot(3,1,1);
stem(nx,x);
xlabel('n');ylabel('x(n)');
title('signal x(n)');
subplot(3,1,2);
stem(nh,h);
xlabel('n');ylabel('h(n)'); 
title('signal h(n)');
n=(0:1:length(x)+length(h)-2);
subplot(3,1,3);
c=conv(x,h);
stem(n,c,'k');
xlabel('n');
ylabel('x(n)');
title('signal c= x(n)*h(n)');
