clc;clear all;close all;
b=[1];
a=[1 -0.9];
zplane(b,a);
w=[-200:1:200]*pi/100;
H=freqz(b,a,w);
magH=abs(H);
angH=angle(H);
figure;
subplot(2,1,1);
plot(w/pi,magH);
xlabel('FREQUNECY IN pi UNIT');
ylabel('--MAGNITUDE--');
title('MAGNITUDE RESPONSE');
subplot(2,1,2);
plot(w/pi,angH);
xlabel('FREQUENCY IN pi UNIT');
ylabel('PHASE IN pi UNIT');
title('PHASE RESPONSE');